server:
  port: 8500
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 配置路由，注意这里是个列表，每一项都包含了很多信息
      routes:
      - id: borrow-service # 路由名称
        uri: lb://borrow-service # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
        predicates: # 路由规则，断言什么请求会被路由转发
        - Path=/borrow/**